### ISSUE TITLE
Rename the package to have a different name from the repository

### ISSUE THREAD

**Issue by smguo** [czbiohub/reconstruct-order#83]
**Are you asking for this feature to solve a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mattersoflight** [comment]
This issue is related to #61. It is best to keep package name the same (reconstructOrder), while changing the repository name, e.g., reconstruct-order. @bryantChhun, does doing so affect pypi distribution?
